apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-nginx
  labels:
    app: daemon-app
spec:
  selector:
    matchLabels:
      name: daemon-app
  template:
    metadata:
      labels:
        name: daemon-app
    spec:
      containers:
      - name: ct-nginx
        image: nginx
        ports:
          - containerPort: 80