apiVersion: v1
kind: Pod
metadata:
  name: pod-env
spec:
  containers:
  - image: nginx
    name: ct-env
    env:
      - name: username
        value: rafiryd
      - name: password
        value: jjj