apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  selector:
    app: app-nginx
  template:
    metadata:
      name: app-nginx
      labels:
        app: app-nginx
    spec:
      containers:
      - name: ct-nginx
        image: nginx
        ports:
        - containerPort: 80