apiVersion: v1
kind: Pod
metadata:
  name: pod1-notoleration
spec:
  containers:
  - name: ct-nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    tolerations:
    - key: "ready"
      operator: "Equal"
      value: "yes"
      effect: "NoSchedule"