apiVersion: v1
kind: Pod
metadata:
  name: pod-no-tolerate
spec:
  containers:
  - name: ct-nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  tolerations:
  - key: "ready"
    operator: "Equal"
    value: "no"
    effect: "NoExecute"
    tolerationSeconds: 60
