apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-require
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - sata
  containers:
  - name: ct-affinity-require
    image: nginx
    imagePullPolicy: IfNotPresent